# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        # 固定窗口大小
        self.setFixedSize(self.width(), self.height())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 351, 331))
        self.label.setObjectName("label")
        
        #添加一个文本框，用于显示识别结果
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 450, 351, 71))
        self.textBrowser.setObjectName("textBrowser")

        self.pushButton_detect_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_detect_img.setGeometry(QtCore.QRect(540, 90, 101, 41))
        self.pushButton_detect_img.setObjectName("pushButton_load")
        self.pushButton_opencamera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_opencamera.setGeometry(QtCore.QRect(540, 160, 101, 41))
        self.pushButton_opencamera.setObjectName("pushButton_opencamera")
        self.pushButton_closecmaera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_closecmaera.setGeometry(QtCore.QRect(540, 230, 101, 41))
        self.pushButton_closecmaera.setObjectName("pushButton_closecmaera")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(540, 300, 101, 41))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_recode = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_recode.setGeometry(QtCore.QRect(540, 370, 101, 41))
        self.pushButton_recode.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # 设置窗口背景为黑色
        self.centralwidget.setStyleSheet('background-color: #e8ecef;')
        self.label.setText(_translate("MainWindow", ""))
        self.label.setStyleSheet('font:14px;')
        self.label.setStyleSheet('border-width: 1px;border-style: solid;'
                                 'border - color: #dcd3b2;'
                                 'background-color: #eaf4fc;'
                                 'border-radius:10px;'
        )
        self.textBrowser.setStyleSheet('font:14px;')
        self.textBrowser.setStyleSheet('border-width: 1px;border-style: solid;'
                                 'border - color: #dcd3b2;'
                                 'background-color: #eaf4fc;'
                                 'border-radius:10px;'
        )
        self.pushButton_detect_img.setText(_translate("MainWindow", "检测图片"))
        self.pushButton_opencamera.setText(_translate("MainWindow", "打开摄像头识别"))
        self.pushButton_closecmaera.setText(_translate("MainWindow", "关闭摄像头"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))
        self.pushButton_recode.setText(_translate("MainWindow", "录入人脸信息"))
